---
title:  "Software Carpentry"
subtitle: "@ Uni Zurich"
shorttitle: "SWC Zurich"
author:
- name: Ulrich Bergmann
  short: Bergmann
  speaker: false
- name: Lachlan Deer
  short: Deer
  speaker: true
- name: Julian Langer
  short: Langer
  speaker: false
useshortauthors: true
toc: false
date: February 2019
section-titles: true
...
